catalog/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("products/", views.ProductListAPIView.as_view(), name="products_list"),
]

catalog/urls.py
from django.urls import path, include
from . import views

app_name = "catalog"

urlpatterns = [
    path("", views.catalog, name="catalog"),
    path("api/", include("catalog.api.urls")),
    # path('categories', views.catalog, name='catalog'),
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "product/detail/<slug:slug>",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
]

textile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, register_converter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenBlacklistView,
)
from . import views
from . import convertors

register_converter(convertors.FourDigitYearConverter, "yyyy")

urlpatterns = [
    path("", views.index, name="index"),
    
    path("admin/", admin.site.urls),
    
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/blacklist/", TokenBlacklistView.as_view(), name="token_blacklist"),

    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("contacts/", views.contacts_view, name="contacts"),
    path("archive/<yyyy:year>/", lambda req, year: HttpResponse(f"<h1> {year} </h1>")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.http_404_handler

catalog/models.py
import os
from django.conf import settings
from datetime import date
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models
from django_extensions.db.models import TimeStampedModel

def category_image_upload_to(instance, filename):
    return f'images/category/{date.today()}/{filename}'

def product_image_upload_to(instance, filename):
    return f'images/product/{date.today()}/{filename}'

class Category(TimeStampedModel):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=category_image_upload_to, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    # def get_absolute_url(self):
    #     return reverse('catalog:category_detail', kwargs={'slug': self.slug})

class ProductType(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.slug

# Create your models here.
class Product(TimeStampedModel):
    slug = models.SlugField()
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=product_image_upload_to, null=True, blank=True)
    price = models.PositiveIntegerField()

    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="products")
    type = models.ForeignKey(ProductType, on_delete=models.PROTECT, related_name="products")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_detail', kwargs={'slug': self.slug})

catalog/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    confirm_published = forms.BooleanField(required=False, label='Подтвердить публикацию')

    class Meta:
        model = Product
        fields = '__all__'
    
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        
        if name and description and name == description:
            raise forms.ValidationError("Название не должно совпадать с описанием")

textile/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label="Ваше имя")
    email = forms.EmailField(label="Ваш email")
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")

catalog/api/views.py
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from catalog.models import Product
from .serializers import ProductSerializer


class ProductListAPIView(ListAPIView):
    queryset = Product.objects.all()
    permission_classes = [IsAuthenticated]
    serializer_class = ProductSerializer

catalog/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, DetailView
from .models import Category, Product
from .forms import ProductForm


# Create your views here.
def catalog(request):
    return render(
        request,
        "catalog/catalog.html",
        {"categories": Category.objects.all()},
    )


# def product_create(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             form.save()  # Сохранение объекта модели в базу данных
#             return redirect('product_list')
#     else:
#         form = ProductForm()
#     return render(request, 'product_form.html', {'form': form})


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    # success_url = reverse_lazy('article_success')  # Если не указывать - get_absolute_url модели

class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/product_detail.html"


# def product_update(request, slug):
#     product = get_object_or_404(Product, slug=slug)
#     if request.method == 'POST':
#         form = ProductForm(request.POST, instance=product)
#         if form.is_valid():
#             form.save()  # Обновление объекта модели
#             return redirect('product_detail', slug=product.slug)
#     else:
#         form = ProductForm(instance=product)
#     return render(request, 'product_form.html', {'form': form})

textile/views.py
from django.shortcuts import render, redirect
from django.views.generic import RedirectView
from .forms import ContactForm


def index(request):
    return render(request, "index.html")

def http_404_handler(request, exc):
    return render(request, "http_404.html")


def contacts_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            # Обработка данных формы
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            # Например, отправка email или сохранение в базе данных
            return redirect("index")
    else:
        form = ContactForm()
    return render(request, "contacts.html", {"form": form})

catalog/templates/catalog.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Catalog" as title %}
    {% build_title title %}
{% endblock %}

{% block content %}
    <h3>Current time: {% current_time "%Y-%m-%d %H:%M" %}</h3>
    <p>{{ xss|safe }}</p>

    <ul>
        {% for category in categories %}
        <li class="{% cycle 'li1' 'li2' %}">
            <h2>{{ category.name }}</h2>
            <img src="{{ category.image.url }}" alt="{{ category.name }}">
            <p>{{ category.description }}</p>
            <p>Fabrics: {{ category.fabrics.all }}</p>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

catalog/templates/catalog/catalog.html
{% extends "index.html" %}
{% load i18n %}
{% load static %}

{% block title %}
    {% trans "Catalog" as title %}
    {% build_title title %}
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'assets/catalog.css' %}">
{% endblock %}
{% block scripts %} 
    <script src="{% static 'catalog.js' %}"></script>
{% endblock %}

{% block content %}
    <section id="page-catalog">

    </section>
{% endblock %}

catalog/templates/catalog/product_detail.html
<!-- templates/article_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ product.name }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h1>{{ product.name }}</h1>
    <p class="text-muted">Создано: {{ product.created }}</p>
    <div class="content">
        {{ product.description|linebreaks }}
        <p><img src="{{ product.image.url }}" alt=""></p>
    </div>
    <a href="{% url 'catalog:catalog' %}" class="btn btn-secondary mt-3">Назад к списку</a>
</div>
</body>
</html>

catalog/templates/catalog/product_form.html
<!-- templates/article_form.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Создать/Редактировать статью</title>
</head>
<body>
<div>
    <h1>Создать/Редактировать статью</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" onsubmit="return false">Сохранить</button>
    </form>
</div>
</body>
</html>

textile/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}UTextile{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />
    {% block styles %} {% endblock %}
  </head>
  <body>
    {% include 'header.html' %}

    <main>
        {% block content %} {% endblock %} 
    </main>

    {% include 'footer.html' %} 

    <script src="{% static 'scripts/utils.js' %}"></script>
    {% block scripts %} {% endblock %}
  </body>
</html>

textile/templates/contacts.html
<!-- templates/contact.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Контакты</title>
</head>
<body>
    <h1>Свяжитесь с нами</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
</body>
</html>

textile/templates/footer.html
<footer>
  <div class="footer-top">
    <div class="footer-column">
      <h4>Company Logo</h4>
    </div>
    <div class="footer-column">
      <h4>COMPANY</h4>
      <ul>
        <li><a href="#">How it works</a></li>
        <li><a href="#">Pricing</a></li>
        <li><a href="#">Docs</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4>RESOURCES</h4>
      <ul>
        <li><a href="#">Blog post name list</a></li>
        <li><a href="#">Blog post name list</a></li>
        <li><a href="#">Blog post name list</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4>ABOUT</h4>
      <ul>
        <li><a href="#">Terms & Conditions</a></li>
        <li><a href="#">Privacy policy</a></li>
      </ul>
      <div class="social-links">
        <a href="#" aria-label="Twitter">&#x1F426;</a>
        <a href="#" aria-label="LinkedIn">&#128101;</a>
        <a href="#" aria-label="Facebook">&#128100;</a>
      </div>
    </div>
  </div>
  <div class="footer-bottom">&copy; {% now "Y"%} {{ site_name }}</div>
</footer>

textile/templates/header.html
<header>
    <div class="logo">
      <a href="{% url 'index' %}">
        Company Logo
      </a>
    </div>
    <div class="header-right">
      <!-- Навигация -->
      <nav>
        <ul id="nav-list">
          <li><a href="{% url 'catalog:catalog' %}">Catalog</a></li>
          <li><a href="#">User Examples</a></li>
          <li><a href="#">Pricing</a></li>
          <li><a href="#">Resources</a></li>
          <li><a href="#">Docs</a></li>
        </ul>
      </nav>
      <!-- Кнопка гамбургера (только на моб.экранах) -->
      <div class="hamburger" id="hamburger-btn">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <!-- Кнопка Get Started -->
      <button class="btn-get-started">Get Started</button>
    </div>
  </header>

textile/templates/http404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ site_name }}</title>
</head>
<body>
    <h1>Requested page not found...</h1>
</body>
</html>

textile/templates/index.html
{% extends "base.html" %}

{% block content %}

  <section class="hero">
    <div class="hero-image"></div>
    <div class="hero-content">
      <h1>UTextile</h1>
      <p>
        UTextile is a textile company that sells a variety of textile products.
        Our products are made from the finest materials and are designed to last.
        Check out our catalog to see our products.
      </p>
      <button class="btn-get-started">Get Started</button>
    </div>
  </section>

  <!-- Секция "Pricing" -->
  <section class="pricing-section">
    <h2>Welcome to UTextile</h2>
    <p>
        UTextile is a textile company that sells a variety of textile products.
        Our products are made from the finest materials and are designed to last.
        Check out our <a href="{% url 'catalog:catalog' %}">catalog</a> to see our products.
    </p>
    <div class="card-list">
      <div class="card">
        <div class="image"></div>
        <h3>Lorem ipsum dolor</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Learn more &rarr;</a>
      </div>
      <div class="card">
        <div class="image"></div>
        <h3>Lorem ipsum dolor</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Learn more &rarr;</a>
      </div>
      <div class="card">
        <div class="image"></div>
        <h3>Lorem ipsum dolor</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Learn more &rarr;</a>
      </div>
      <div class="card">
        <div class="image"></div>
        <h3>Lorem ipsum dolor</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Learn more &rarr;</a>
      </div>
    </div>
  </section>

  {% endblock %}